openapi: 3.0.3
info:
  title: 'Alumni Club API'
  description: 'Simple yet powerful api for alumni club app'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/user:
    get:
      summary: "User endpoint\nThis endpoint returns the authenticated user's data."
      operationId: userEndpointThisEndpointReturnsTheAuthenticatedUsersData
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Auth
      security: []
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address. Must be at least 8 characters. Must not be greater than 256 characters.'
                  example: dreinger@example.com
                password:
                  type: string
                  description: 'Must be at least 6 characters. Must not be greater than 256 characters.'
                  example: 'K][z60uW$=MG'
              required:
                - email
                - password
      security: []
  /api/register:
    post:
      summary: ''
      operationId: postApiRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 256 characters.'
                  example: uthcfuxzurjlltingnjtxttk
                email:
                  type: string
                  description: 'Must be a valid email address. Must be at least 8 characters. Must not be greater than 256 characters.'
                  example: zemlak.estel@example.org
              required:
                - name
                - email
      security: []
  /api/change-initial-password:
    put:
      summary: ''
      operationId: putApiChangeInitialPassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 256 characters.'
                  example: 'rpGtx}G'
              required:
                - password
      security: []
  /api/change-password:
    put:
      summary: ''
      operationId: putApiChangePassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/change-details:
    patch:
      summary: ''
      operationId: patchApiChangeDetails
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date_of_birth:
                  type: string
                  description: 'Must be a valid date in the format <code>d-m-Y</code>.'
                  example: 15-07-2024
                gender:
                  type: string
                  description: ''
                  example: quidem
                email_visible:
                  type: boolean
                  description: ''
                  example: true
                phone_number:
                  type: string
                  description: 'Must match the regex /^\+381[0-9]{8,9}$/.'
                  example: '+38163122737'
                phone_number_visible:
                  type: boolean
                  description: ''
                  example: false
                uni_start_year:
                  type: integer
                  description: 'Must be 4 digits.'
                  example: 12
                uni_finish_year:
                  type: integer
                  description: 'Must be 4 digits.'
                  example: 13
                bio:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 512 characters.'
                  example: gblvrbqxqfwifxnhomstrjy
              required:
                - date_of_birth
                - gender
                - email_visible
                - phone_number
                - phone_number_visible
                - uni_start_year
                - uni_finish_year
      security: []
  /api/job/create:
    post:
      summary: ''
      operationId: postApiJobCreate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                comapny_name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 16 characters.'
                  example: fqbmrecegytybu
                position:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 24 characters.'
                  example: qwuzbljhmpsz
                start_date:
                  type: string
                  description: 'Must be a valid date. Must be a date before <code>end_date</code>.'
                  example: '2021-06-04'
                end_date:
                  type: string
                  description: 'Must be a valid date. Must be a date after <code>start_date</code>.'
                  example: '2104-11-14'
                desc:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 256 characters.'
                  example: ncgikbhpnftdaw
              required:
                - comapny_name
                - position
                - start_date
                - end_date
      security: []
tags:
  -
    name: Auth
    description: ''
  -
    name: Endpoints
    description: ''
