openapi: 3.0.3
info:
  title: 'Alumni Club API'
  description: 'Simple yet powerful api for alumni club app'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/login:
    post:
      summary: Login
      operationId: login
      description: 'This endpoint is used for user logging in.'
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: "User's email address"
                  example: john@doe.com
                password:
                  type: string
                  description: "User's password"
                  example: password
              required:
                - email
                - password
      security: []
  /api/user:
    get:
      summary: 'Get user'
      operationId: getUser
      description: "This endpoint returns the authenticated user's data."
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Auth
  /api/register:
    post:
      summary: Register
      operationId: register
      description: "This endpoint is used for registering new user's into app."
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "User's name"
                  example: 'John Doe'
                email:
                  type: string
                  description: "User's email address"
                  example: john@doe.com
              required:
                - name
                - email
  /api/change-initial-password:
    put:
      summary: 'Change initial password'
      operationId: changeInitialPassword
      description: "This endpoint is used only for changing user's initial password."
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 256 characters.'
                  example: 'vxleU~X[krr'
              required:
                - password
  /api/change-password:
    put:
      summary: 'Change password'
      operationId: changePassword
      description: 'This endpoint is used for changing user passowrd.'
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: 'New password'
                  example: password
                password_confirmation:
                  type: string
                  description: 'New password confirmed'
                  example: password
              required:
                - password
                - password_confirmation
  /api/change-details:
    patch:
      summary: 'Change user details'
      operationId: changeUserDetails
      description: 'This endpoint is used for changing user details'
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date_of_birth:
                  type: string
                  description: 'Must be a valid date in the format d-m-Y'
                  example: 10-04-1997
                gender:
                  type: string
                  description: "Must be either 'male' or 'female'"
                  example: male
                email_visible:
                  type: boolean
                  description: ''
                  example: false
                phone_number:
                  type: string
                  description: 'Must be a phone number that starts with +381'
                  example: '+3816060606'
                phone_number_visible:
                  type: boolean
                  description: ''
                  example: false
                uni_start_year:
                  type: integer
                  description: ''
                  example: 2020
                uni_finish_year:
                  type: integer
                  description: ''
                  example: 2023
                bio:
                  type: string
                  description: "User's biography"
                  example: ''
              required:
                - date_of_birth
                - gender
                - email_visible
                - phone_number
                - phone_number_visible
                - uni_start_year
                - uni_finish_year
  /api/jobs:
    post:
      summary: 'Create job'
      operationId: createJob
      description: 'This endpoint is used for creating job for authenticated user.'
      parameters: []
      responses: {  }
      tags:
        - Jobs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                company_name:
                  type: string
                  description: 'Company name'
                  example: 'Moto IT'
                position:
                  type: string
                  description: ''
                  example: 'Front-end Develper'
                start_date:
                  type: string
                  description: 'Must be a valid date in the format d-m-Y'
                  example: 10-04-1997
                end_date:
                  type: string
                  description: 'Must be a valid date in the format d-m-Y'
                  example: 15-05-1997
                desc:
                  type: string
                  description: 'Describe what you do...'
                  example: ''
              required:
                - company_name
                - position
                - start_date
                - end_date
                - desc
tags:
  -
    name: Auth
    description: ''
  -
    name: Jobs
    description: ''
