openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/healthcheck:
    get:
      summary: ''
      operationId: getApiHealthcheck
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: up
                  services:
                    database: up
                    redis: up
                properties:
                  status:
                    type: string
                    example: up
                  services:
                    type: object
                    properties:
                      database:
                        type: string
                        example: up
                      redis:
                        type: string
                        example: up
      tags:
        - Endpoints
      security: []
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address. Must be at least 8 characters. Must not be greater than 256 characters.'
                  example: boyle.alexys@example.net
                password:
                  type: string
                  description: 'Must be at least 6 characters. Must not be greater than 256 characters.'
                  example: '+m([km'
              required:
                - email
                - password
      security: []
  /api/register:
    post:
      summary: ''
      operationId: postApiRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 256 characters.'
                  example: zmlcqplfbcitw
                email:
                  type: string
                  description: 'Must be a valid email address. Must be at least 8 characters. Must not be greater than 256 characters.'
                  example: tomasa28@example.net
              required:
                - name
                - email
      security: []
  /api/change-initial-password:
    put:
      summary: ''
      operationId: putApiChangeInitialPassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 256 characters.'
                  example: ~m9@3@jz9-d7y
              required:
                - password
      security: []
  /api/change-password:
    put:
      summary: ''
      operationId: putApiChangePassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/change-details:
    patch:
      summary: ''
      operationId: patchApiChangeDetails
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date_of_birth:
                  type: string
                  description: 'Must be a valid date in the format <code>d-m-Y</code>.'
                  example: 15-07-2024
                gender:
                  type: string
                  description: ''
                  example: ut
                email_visible:
                  type: boolean
                  description: ''
                  example: false
                phone_number:
                  type: string
                  description: 'Must match the regex /^\+381[0-9]{8,9}$/.'
                  example: '+38109989198'
                phone_number_visible:
                  type: boolean
                  description: ''
                  example: true
                uni_start_year:
                  type: integer
                  description: 'Must be 4 digits.'
                  example: 18
                uni_finish_year:
                  type: integer
                  description: 'Must be 4 digits.'
                  example: 2
                bio:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 512 characters.'
                  example: zcjbqrpgwdcprgwuitykq
              required:
                - date_of_birth
                - gender
                - email_visible
                - phone_number
                - phone_number_visible
                - uni_start_year
                - uni_finish_year
      security: []
  /api/job/create:
    post:
      summary: ''
      operationId: postApiJobCreate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                comapny_name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 16 characters.'
                  example: dhpsfpdtvelnb
                position:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 24 characters.'
                  example: rqoqnvp
                start_date:
                  type: string
                  description: 'Must be a valid date. Must be a date before <code>end_date</code>.'
                  example: '2019-10-09'
                end_date:
                  type: string
                  description: 'Must be a valid date. Must be a date after <code>start_date</code>.'
                  example: '2040-01-17'
                desc:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 256 characters.'
                  example: jiygzwxjgslpaxneetfhwyl
              required:
                - comapny_name
                - position
                - start_date
                - end_date
      security: []
tags:
  -
    name: Endpoints
    description: ''
